pipeline:
  build-and-push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: "${CI_REPO_OWNER%%io}/${CI_REPO_NAME}"
      tags: latest
    when:
      event:
        - push
branches:
  - master
